//! Cross-language parity: the Rust scorer must reproduce Python's numbers.
//!
//! This is the test the whole bundle format exists to make possible. A model
//! that scores differently in the browser than it did in training is silently
//! wrong for every patient, and nothing else in the pipeline would catch it —
//! the trees load, the scores look plausible, and the thresholds are subtly
//! misapplied.
//!
//! Fixtures are regenerated by `scripts/generate_parity_fixture.py`.

use penux_scorer::Bundle;
use serde::Deserialize;

#[derive(Deserialize)]
struct Cases {
    /// `null` marks an unmeasured lab and becomes NaN.
    features: Vec<Vec<Option<f64>>>,
    expected: Vec<f64>,
}

#[test]
fn matches_python_reference() {
    let bundle_json = match std::fs::read_to_string("tests/fixture_bundle.json") {
        Ok(text) => text,
        Err(_) => {
            eprintln!("fixture missing; run scripts/generate_parity_fixture.py");
            return;
        }
    };
    let cases_json = std::fs::read_to_string("tests/fixture_cases.json")
        .expect("fixture_cases.json must accompany fixture_bundle.json");

    let bundle: Bundle = serde_json::from_str(&bundle_json).expect("bundle parses");
    let cases: Cases = serde_json::from_str(&cases_json).expect("cases parse");

    assert_eq!(
        cases.features.len(),
        cases.expected.len(),
        "fixture is malformed: feature rows and expected scores differ in length"
    );

    let mut worst: f64 = 0.0;
    for (row, expected) in cases.features.iter().zip(&cases.expected) {
        let values: Vec<f64> = row.iter().map(|v| v.unwrap_or(f64::NAN)).collect();
        let actual = bundle.score_row(&values).expect("row scores");
        worst = worst.max((actual - expected).abs());
    }

    // Tolerance is for f64 summation order across the two implementations, not
    // for genuine disagreement; anything above this means a real divergence.
    assert!(
        worst < 1e-9,
        "Rust and Python disagree by {worst:e}, above the 1e-9 tolerance"
    );
    eprintln!("parity verified over {} rows, max diff {worst:e}", cases.expected.len());
}

#[test]
fn rejects_wrong_feature_count() {
    let Ok(bundle_json) = std::fs::read_to_string("tests/fixture_bundle.json") else {
        return;
    };
    let bundle: Bundle = serde_json::from_str(&bundle_json).expect("bundle parses");

    // Silently scoring a short vector would read the wrong columns rather than
    // fail, which is worse than an error.
    assert!(bundle.score_row(&[0.0, 1.0]).is_err());
}
