"""Detect whether Wordfence is installed and, when possible, its version.

Signals used (all passive / low-noise GET requests):
  - Presence of /wp-content/plugins/wordfence/ assets
  - readme.txt "Stable tag" of the wordfence plugin
  - Wordfence-specific response headers / cookies
  - The Wordfence "403 Forbidden" block page signature

Python 3.5 compatible.
"""

import re

from ..report import Finding

_README_PATHS = [
    "wp-content/plugins/wordfence/readme.txt",
]
_ASSET_PATHS = [
    "wp-content/plugins/wordfence/css/wordfenceBox.css",
    "wp-content/plugins/wordfence/js/admin.js",
]
_STABLE_TAG = re.compile(r"Stable tag:\s*([0-9][0-9A-Za-z.\-]*)", re.I)
_BLOCK_SIGNATURES = [
    "Generated by Wordfence",
    "your access to this site has been limited",
    "wfls-",  # Wordfence Login Security markup
]


def detect_version(client):
    for path in _README_PATHS:
        r = client.get(path)
        if r.status == 200 and "wordfence" in r.body.lower():
            m = _STABLE_TAG.search(r.body)
            if m:
                return m.group(1), path
            return None, path
    return None, None


def run(client, report, opts):
    found = False

    version, src = detect_version(client)
    if src:
        found = True
        if version:
            report.add(Finding(
                "fingerprint", "info",
                "Wordfence detected, version {0}".format(version),
                detail="Version disclosed via {0}. Public readme.txt exposes the "
                       "exact plugin version, aiding targeted CVE lookup.".format(src),
                evidence="{0} -> Stable tag: {1}".format(src, version),
            ))
            opts["wordfence_version"] = version
        else:
            report.add(Finding(
                "fingerprint", "info", "Wordfence detected (version unknown)",
                detail="Plugin readme reachable at {0} but no Stable tag parsed.".format(src),
            ))

    for path in _ASSET_PATHS:
        r = client.get(path)
        if r.status == 200:
            found = True
            report.add(Finding(
                "fingerprint", "info", "Wordfence plugin assets reachable",
                detail="Static plugin assets are directly reachable, confirming the "
                       "plugin is installed.",
                evidence="{0} -> HTTP 200".format(path),
            ))
            break

    # Probe a path likely to trip the WAF/login-security block page.
    r = client.get("?author=1")
    if any(sig.lower() in r.body.lower() for sig in _BLOCK_SIGNATURES):
        found = True
        report.add(Finding(
            "fingerprint", "info", "Wordfence block page signature observed",
            detail="Response matched a known Wordfence block/limit page signature.",
            evidence="status={0} on ?author=1".format(r.status),
        ))

    # Wordfence WAF cookies.
    r = client.get("wp-login.php")
    cookies = r.headers.get("Set-Cookie", "")
    if "wfwaf" in cookies.lower():
        found = True
        report.add(Finding(
            "fingerprint", "info", "Wordfence WAF cookie present",
            detail="A wfwaf-* cookie indicates the Wordfence firewall is active.",
            evidence="Set-Cookie contains wfwaf",
        ))

    if not found:
        report.add(Finding(
            "fingerprint", "info", "Wordfence not conclusively detected",
            detail="No Wordfence signatures found. It may be absent, or hardened to "
                   "hide assets and readme.txt.",
        ))
    opts["wordfence_detected"] = found
