"""Probe Wordfence firewall behaviour with benign, signature-like payloads.

This does NOT attempt exploitation. It sends harmless probe strings that resemble
common attack signatures (in query params only) and observes whether the firewall
blocks, throttles, or passes them. Use it to answer "is the WAF actually inspecting
this traffic, and in which mode?" on your own lab.

Python 3.5 compatible.
"""

from ..report import Finding

# Benign probes: strings that look like attack signatures but do nothing.
# They target query parameters only and never touch a real vulnerable sink.
_PROBES = [
    ("sqli", "id=1%20AND%201=1--", "Basic SQLi signature"),
    ("union", "id=-1%20UNION%20SELECT%201,2,3--", "UNION SELECT signature"),
    ("xss", "s=<script>alert(1)</script>", "Reflected XSS signature"),
    ("lfi", "file=../../../../etc/passwd", "Path traversal signature"),
    ("rce", "cmd=;cat%20/etc/passwd", "Command injection signature"),
    ("wpscan_ua", "", "User-Agent based blocking"),
]

_BLOCK_MARKERS = [
    "generated by wordfence",
    "your access to this site has been limited",
    "blocked",
    "forbidden",
]


def _looks_blocked(resp):
    if resp.status in (403, 406, 503):
        return True
    low = resp.body.lower()
    return any(m in low for m in _BLOCK_MARKERS)


def run(client, report, opts):
    baseline = client.get("/")
    baseline_ok = baseline.status in (200, 301, 302)

    blocked = 0
    for name, qs, desc in _PROBES:
        if name == "wpscan_ua":
            resp = client.get("/", extra_headers={"User-Agent": "WPScan v3.8.0"})
        else:
            resp = client.get("/?" + qs)

        if _looks_blocked(resp):
            blocked += 1
            report.add(Finding(
                "waf", "info", "WAF blocked probe: {0}".format(desc),
                detail="Firewall appears to inspect and block '{0}' style "
                       "requests.".format(name),
                evidence="status={0}".format(resp.status),
            ))

    if not opts.get("wordfence_detected"):
        return

    total = len(_PROBES)
    if blocked == 0 and baseline_ok:
        report.add(Finding(
            "waf", "medium", "Wordfence firewall not blocking common signatures",
            detail="No benign attack-signature probe was blocked. The WAF may be in "
                   "'Learning Mode', disabled, or Extended Protection not active. "
                   "Verify optimization/installation in Wordfence > Firewall.",
            references=["https://www.wordfence.com/help/firewall/optimizing-the-firewall/"],
        ))
    elif blocked < total - 1:
        report.add(Finding(
            "waf", "low",
            "Wordfence firewall partial coverage ({0}/{1} blocked)".format(blocked, total),
            detail="Some signature classes pass through. In a real assessment, review "
                   "which categories are uncovered and whether Extended Protection is enabled.",
        ))
    else:
        report.add(Finding(
            "waf", "info",
            "Wordfence firewall active ({0}/{1} probes blocked)".format(blocked, total),
            detail="Firewall is inspecting requests and blocking signature-like traffic.",
        ))
